debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.usafe.fast: debug
    org.springframework.web.server: debug
    org.hibernate.type.descriptor.sql: trace
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: huvi
    password: thisisTESTpw!@#$
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
---

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mariaDB
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always


